name: Publish image to Docker Hub
on:
  push:
    tags:
      - v*

jobs:
  push_to_registry:
    name: Push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name:  Setup Node.js
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}

      - run: npm ci
      - run: npm run build

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: refactr/cli
          tag_with_ref: true

      - name: Publish to npm registry
        run: npm publish --access public --tag ${{ steps.steps.get_version.outputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
